# Generated by Django 3.0.6 on 2020-06-10 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('predatoryjournals', '0002_auto_20200609_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
