# Generated by Django 3.0.6 on 2020-06-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predatoryjournals', '0003_listing_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='url',
            field=models.URLField(default='?'),
        ),
    ]
